name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: grade
      id: grade
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: grade
        setup-command: ''
        command: text.py
        input: ''
        expected-output: ''
        comparison-method: contains
        timeout: 1
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        GRADE_RESULTS: "${{steps.grade.outputs.result}}"
      with:
        runners: grade
